### ISSUE TITLE
'message': "Unknown parameter 'description'", 'code': -32602

### ISSUE THREAD

**Issue by javiervargas** [renepickhardt/lightning-helpers#2]
Hi Rene,

As we said in the chat, to correct the first error that I had:

'ImportError: No module named' lightning '

the procedure is install python3, install pip3 and then install pylightning.
Then I tried to send 1000 satohis using your node_id as you suggested and throw an error about the description param.

`javier@nlp:/home/javier/lightning-helpers/pay_anyone_without_invoice$ python3.5 pay_without_invoice.py 03efccf2c383d7bf340da9a3f02e2c23104a0e4fe8ac1a880c8e2dc92fbdacd9df 1000
standard route to node:  03efccf2c383d7bf340da9a3f02e2c23104a0e4fe8ac1a880c8e2dc92fbdacd9df
[
  {
    "channel": "540420:1240:1",
    "delay": 311,
    "id": "02529db69fd2ebd3126fb66fafa234fc3544477a23d509fe93ed229bb0e92e4fb8",
    "msatoshi": 1000872
  },
  {
    "channel": "540398:2238:1",
    "delay": 167,
    "id": "03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d",
    "msatoshi": 1000820
  },
  {
    "channel": "540711:1174:0",
    "delay": 23,
    "id": "024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365",
    "msatoshi": 1000810
  },
  {
    "channel": "537914:2372:0",
    "delay": 9,
    "id": "03efccf2c383d7bf340da9a3f02e2c23104a0e4fe8ac1a880c8e2dc92fbdacd9df",
    "msatoshi": 1000000
  }
]
motified route over node 03efccf2c383d7bf340da9a3f02e2c23104a0e4fe8ac1a880c8e2dc92fbdacd9df back to myself
[
  {
    "channel": "540420:1240:1",
    "delay": 1152,
    "id": "02529db69fd2ebd3126fb66fafa234fc3544477a23d509fe93ed229bb0e92e4fb8",
    "msatoshi": 1000872
  },
  {
    "channel": "540398:2238:1",
    "delay": 1008,
    "id": "03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d",
    "msatoshi": 1000820
  },
  {
    "channel": "540711:1174:0",
    "delay": 864,
    "id": "024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365",
    "msatoshi": 1000810
  },
  {
    "channel": "537914:2372:0",
    "delay": 720,
    "id": "03efccf2c383d7bf340da9a3f02e2c23104a0e4fe8ac1a880c8e2dc92fbdacd9df",
    "msatoshi": 1000000
  },
  {
    "channel": "537914:2372:0",
    "delay": 576,
    "id": "024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365",
    "msatoshi": 3240
  },
  {
    "channel": "540711:1174:0",
    "delay": 432,
    "id": "03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d",
    "msatoshi": 2430
  },
  {
    "channel": "540398:2238:1",
    "delay": 288,
    "id": "02529db69fd2ebd3126fb66fafa234fc3544477a23d509fe93ed229bb0e92e4fb8",
    "msatoshi": 1620
  },
  {
    "channel": "540420:1240:1",
    "delay": 144,
    "id": "0283065d6d5b1fbeaa1f21e62755b4b834c4fabd2765d9522f5a79ec216fec3013",
    "msatoshi": 810
  }
]
{'bolt11': 'lnbc10n1pdu08lhpp55rz0t30a8vzhjw085kmgpxxzfw7yy64eaw7mk64uxw4c0trcm0dqdpawdjkuerhd96xsmm4wskkjmnkda5kxefdxy6nxwfcxqunyde39curgdfhxy6nxcqp29pduy32k5vyaxx8fwm6g8s0q6pl0pds0x56keykzhr79m2dxcacyzxxmvznjru0x2r5ma8hpwd775gaa3jfsaqjmufp7tf6p59d8k2qp9h4yaw', 'expiry_time': 1539812871, 'expires_at': 1539812871, 'payment_hash': 'a0c4f5c5fd3b057939e7a5b68098c24bbc426ab9ebbdbb6abc33ab87ac78dbda'}
Traceback (most recent call last):
  File "pay_without_invoice.py", line 103, in <module>
    flag = pay_without_invoice(nodeid, amount)
  File "pay_without_invoice.py", line 94, in pay_without_invoice
    send_the_payment(fullroute)
  File "pay_without_invoice.py", line 45, in send_the_payment
    res = ln1.sendpay(route, ph, "initial sendpay without invoice")
  File "/usr/local/lib/python3.5/dist-packages/lightning/lightning.py", line 286, in sendpay
    return self.call("sendpay", payload)
  File "/usr/local/lib/python3.5/dist-packages/lightning/lightning.py", line 80, in call
    raise RpcError(method, payload, resp['error'])
lightning.lightning.RpcError: RPC call failed: method: sendpay, payload: {'route': [{'channel': '540420:1240:1', 'msatoshi': 1000872, 'id': '02529db69fd2ebd3126fb66fafa234fc3544477a23d509fe93ed229bb0e92e4fb8', 'delay': 1152}, {'channel': '540398:2238:1', 'msatoshi': 1000820, 'id': '03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d', 'delay': 1008}, {'channel': '540711:1174:0', 'msatoshi': 1000810, 'id': '024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365', 'delay': 864}, {'channel': '537914:2372:0', 'msatoshi': 1000000, 'id': '03efccf2c383d7bf340da9a3f02e2c23104a0e4fe8ac1a880c8e2dc92fbdacd9df', 'delay': 720}, {'channel': '537914:2372:0', 'msatoshi': 3240, 'id': '024a8228d764091fce2ed67e1a7404f83e38ea3c7cb42030a2789e73cf3b341365', 'delay': 576}, {'channel': '540711:1174:0', 'msatoshi': 2430, 'id': '03bb88ccc444534da7b5b64b4f7b15e1eccb18e102db0e400d4b9cfe93763aa26d', 'delay': 432}, {'channel': '540398:2238:1', 'msatoshi': 1620, 'id': '02529db69fd2ebd3126fb66fafa234fc3544477a23d509fe93ed229bb0e92e4fb8', 'delay': 288}, {'channel': '540420:1240:1', 'msatoshi': 810, 'id': '0283065d6d5b1fbeaa1f21e62755b4b834c4fabd2765d9522f5a79ec216fec3013', 'delay': 144}], 'payment_hash': 'a0c4f5c5fd3b057939e7a5b68098c24bbc426ab9ebbdbb6abc33ab87ac78dbda', 'description': 'initial sendpay without invoice'}, error: {'message': "Unknown parameter 'description'", 'code': -32602}
javier@nlp:/home/javier/lightning-helpers/pay_anyone_without_invoice$ 
`
I could not find anything about the description parameter, what is happening?

Thanks

Javier

**Comment by renepickhardt** [comment]
it seems like there is a problem that not all c-lightning nodes accept the description field in pylightning. The error comes from this line of the original c-lightning repo: https://github.com/ElementsProject/lightning/blob/a90c200fcbe8cbbe97cde8a255baf30ce7403d11/lightningd/param.c#L120

I will quickfix this on my side by dropping the description argument in line 45 c.f.: https://github.com/renepickhardt/lightning-helpers/blob/2c03df742ba86b9f019de6bc53172d0f9ce63189/pay_anyone_without_invoice/pay_without_invoice.py#L45

**Comment by javiervargas** [comment]
Done,  now it can't find a route and if I search BOLT it returns an empty string.

`javier@nlp:/home/javier/lightning-helpers/pay_anyone_without_invoice$ /home/javier/lightning/cli/lightning-cli --rpc-file='/tmp/lightning-rpc' listpayments lnbc10n1pdu08lhpp55rz0t30a8vzhjw085kmgpxxzfw7yy64eaw7mk64uxw4c0trcm0dqdpawdjkuerhd96xsmm4wskkjmnkda5kxefdxy6nxwfcxqunyde39curgdfhxy6nxcqp29pduy32k5vyaxx8fwm6g8s0q6pl0pds0x56keykzhr79m2dxcacyzxxmvznjru0x2r5ma8hpwd775gaa3jfsaqjmufp7tf6p59d8k2qp9h4yaw
{
  "payments": [
  ]
}
`
